---
#- name: Include vars from molecule.yml
#  include_vars: molecule.yml

- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: true
  vars:
  vars_files:
    -  molecule.yml
  tasks:
    - name: Destroy resource group and all associated resources
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
        force_delete_nonempty: true
      register: rg

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: rg.changed | bool
